### PR TITLE
BuildForLinux additions

### PR DESCRIPTION
**Pull request by StarkillerX42**
I added a mostly-stable BuildForLinux directory that allows us to build for pretty much any platform actually using pyinstaller. It works on my system, but Elena ran into some strange issues. The readme is thorough enough to allow for testing. Currently, I can't really live-test it because I can't figure out how to connect through STUI, but that has nothing to do with the build.

### CODE REVIEW

**Comment by albireox** [comment]
Sorry for the long delay reviewing this and thanks for doing this.

In principle everything here seems ok to me. I have tested it in my Mac machine and everything *seems* to be working ok on the Apple side. Since most of the changes are on the `BuildForLinux` directory, I'd have no problem merging this.

Can you comment on the problems that Elena found? I have tested it for a few minutes and connected to APO and it seems to work, but I haven't tested it thorougly.

I also see that you've removed a couple asset libraries from the Mac installation. Was there a reason for that? In principle those files are there to support older versions of macOS.

**Comment by StarkillerX42** [comment]
I removed those folders because I didn't see them as important and wasn't aware of their utility to MacOS, so I suppose that's a mistake that should be undone.

The problem Elena found was when she ran pyinstaller on the .spec file. It produced an obscure error and unfortunately I can't remember many details about it other than it was very obscure and hard to trace. I'll ping her and see if we can try to get it again and take a deeper look.

**Comment by StarkillerX42** [comment]
I made a mistake and added some Python 3 commits that aren't supposed to be part of this pull request. I've only ever used GitHub for personal projects before, so I've still got some learning to do. Do you know how to roll back origin/master of my fork to a commit prior to 75bfbe6?

**Comment by albireox** [comment]
If you want to revert a specific commit you can do

```
git revert <COMMIT-ID>
```

and commit the inverse change. If you want to revert all the way to a certain commit you can do

```
git reset <COMMIT-ID>
```
and that should modify your working checkout to that commit.

**Pull request closed without merging**
